writePrologue   :-  nl,
                    write('----------------------------------[ Awal Cerita ]-----------------------------------'), nl, nl,
                    write('    ________'),nl,
                    write('|--[ Claire ]-----------------------------------------------------------------------|'),nl,
                    write('|                                                                                   |'),nl,
                    write('|  Sial!!!!                                                                         |'),nl,
                    write('|                                                                                   |'),nl,
                    write('|-----------------------------------------------------------------------------------|'),nl,
                    write('ketik \"next.\" untuk lanjut'),  nl, read(_),

                    write('    ________'),nl,
                    write('|--[ Claire ]-----------------------------------------------------------------------|'),nl,
                    write('|                                                                                   |'),nl,
                    write('|  Aku ditipu oleh klienku sendiri!!!                                               |'),nl,
                    write('|                                                                                   |'),nl,
                    write('|-----------------------------------------------------------------------------------|'),nl,
                     write('ketik \"next.\" untuk lanjut'), nl, read(_), 

                    write('    ________'),nl,
                    write('|--[ Claire ]-----------------------------------------------------------------------|'),nl,
                    write('|                                                                                   |'),nl,
                    write('|  Sekarang, aku harus melunasi hutang sebesar 20000 gold dalam haktu 1 tahun..     |'),nl,
                    write('|                                                                                   |'),nl,
                    write('|-----------------------------------------------------------------------------------|'),nl,
                     write('ketik \"next.\" untuk lanjut'),  nl, read(_),

                    write('    ________'),nl,
                    write('|--[ Claire ]-----------------------------------------------------------------------|'),nl,
                    write('|                                                                                   |'),nl,
                    write('|  Huh..                                                                            |'),nl,
                    write('|  Bagaimana caranya..                                                              |'),nl,
                    write('|-----------------------------------------------------------------------------------|'),nl,
                     write('ketik \"next.\" untuk lanjut'),  nl, read(_),

                    write('\n|-----------------------------------------------------------------------------------|'),nl,
                    write('|                                                                                   |'),nl,
                    write('|                    * KRING KRING. KRING KRING. KRING KRING *                      |'),nl,
                    write('|                                (suara HP Claire)                                  |'),nl,
                    write('|-----------------------------------------------------------------------------------|'),nl,
                    write('ketik \"next.\" untuk lanjut'),  nl, read(_),

                    write('    ________________'),nl,
                    write('|--[ Kakeknya Claire ]--------------------------------------------------------------|'),nl,
                    write('|                                                                                   |'),nl,
                    write('|  Halo, Claire..                                                                   |'),nl,
                    write('|                                                                                   |'),nl,
                    write('|-----------------------------------------------------------------------------------|'),nl,
                     write('ketik \"next.\" untuk lanjut'),  nl, read(_),

                    write('    ________'),nl,
                    write('|--[ Claire ]-----------------------------------------------------------------------|'),nl,
                    write('|                                                                                   |'),nl,
                    write('|  Halo Kakek. Ada apa?                                                             |'),nl,
                    write('|                                                                                   |'),nl,
                    write('|-----------------------------------------------------------------------------------|'),nl,
                     write('ketik \"next.\" untuk lanjut'),  nl, read(_),

                    write('    ________________'),nl,
                    write('|--[ Kakenya Claire ]---------------------------------------------------------------|'),nl,
                    write('|                                                                                   |'),nl,
                    write('|  Kakek dengar kamu baru saja ditipu klien dan sekarang terlilit hutang.           |'),nl,
                    write('|  Maukah kamu melanjutkan pertanian kakek? Kakek sudah terlalu tua untuk bertani.  |'),nl,
                    write('|  Nanti kamu boleh mengambil hasil pertaniannya..                                  |'),nl,
                    write('|-----------------------------------------------------------------------------------|'),nl,
                     write('ketik \"next.\" untuk lanjut'),  nl, read(_),

                    write('    ________'),nl,
                    write('|--[ Claire ]-----------------------------------------------------------------------|'),nl,
                    write('|                                                                                   |'),nl,
                    write('|  Wah, beneran nih kek?                                                            |'),nl,
                    write('|                                                                                   |'),nl,
                    write('|-----------------------------------------------------------------------------------|'),nl,
                     write('ketik \"next.\" untuk lanjut'),  nl, read(_),
 
                    write('    ________________'),nl,
                    write('|--[ Kakenya Claire ]---------------------------------------------------------------|'),nl,
                    write('|                                                                                   |'),nl,
                    write('|  Tentu saja beneran.                                                              |'),nl,
                    write('|                                                                                   |'),nl,
                    write('|-----------------------------------------------------------------------------------|'),nl,
                     write('ketik \"next.\" untuk lanjut'),  nl, read(_),

                    write('    ________'),nl,
                    write('|--[ Claire ]-----------------------------------------------------------------------|'),nl,
                    write('|                                                                                   |'),nl,
                    write('|  Baiklah, Kek! Aku segera ke sana!                                                |'),nl,
                    write('|                                                                                   |'),nl,
                    write('|-----------------------------------------------------------------------------------|'),nl,
                     write('ketik \"next.\" untuk lanjut'),  nl, read(_),

                    nl,
                    write('|-----------------------------------------------------------------------------------|'),nl,
                    write('|                                                                                   |'),nl,
                    write('|                    Dari sinilah hidup baru Claire dimulai..                       |'),nl,
                    write('|                                                                                   |'),nl,
                    write('|-----------------------------------------------------------------------------------|'),nl, nl,
                    write('-----------------[ Jika butuh bantuan, ketikkan command "help." ]-------------------'), nl.



